//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLQLHG
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int STT { get; set; }
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaSP { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
